export const ROUTES = {
  approvalWorkflows: "/approval-workflows",
  approvals: "/approvals",
  attachments: "/attachments",
  auditLogs: "/audit-logs",
  budgets: "/budgets",
  changePassword: "/change-password",
  dashboard: "/dashboard",
  departments: "/departments",
  home: "/",
  invoices: "/invoices",
  login: "/login",
  payments: "/payments",
  platformBilling: "/platform/billing",
  platformCompanies: "/platform/companies",
  platformPlans: "/platform/plans",
  platformSubscriptions: "/platform/subscriptions",
  purchaseOrders: "/purchase-orders",
  purchaseRequests: "/purchase-requests",
  reportApprovals: "/reports/approvals",
  reportInvoices: "/reports/invoices",
  reportPayments: "/reports/payments",
  reportPurchaseOrders: "/reports/purchase-orders",
  reportPurchaseRequests: "/reports/purchase-requests",
  reports: "/reports",
  rolesPermissions: "/roles-permissions",
  rfqs: "/rfqs",
  settings: "/settings",
  users: "/users",
  vendors: "/vendors",
} as const;

export type RouteKey = keyof typeof ROUTES;
export type RoutePath = (typeof ROUTES)[RouteKey];
