"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import { X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useForm, useWatch } from "react-hook-form";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  usePlatformCompanySubscription,
} from "@/features/platform/companies/hooks";
import type {
  PlatformCompany,
  PlatformPlan,
} from "@/features/platform/companies/types";
import { getApiErrorMessage } from "@/lib/api/client";
import { cn } from "@/lib/utils/cn";
import { useCreatePlatformBillingInvoice } from "../hooks";
import {
  createPlatformBillingInvoiceSchema,
  type CreatePlatformBillingInvoiceValues,
} from "../schemas";
import {
  formatBillingMoney,
  getBillingMutationError,
  normalizeOptional,
} from "../utils";

type CreatePlatformInvoiceDrawerProps = {
  companies: PlatformCompany[];
  isOpen: boolean;
  onClose: () => void;
  plans: PlatformPlan[];
};

const emptyValues: CreatePlatformBillingInvoiceValues = {
  amount: 0,
  billingPeriodEnd: "",
  billingPeriodStart: "",
  companyId: "",
  dueDate: "",
  notes: "",
  planId: "",
  subscriptionId: "",
};

export function CreatePlatformInvoiceDrawer({
  companies,
  isOpen,
  onClose,
  plans,
}: CreatePlatformInvoiceDrawerProps) {
  const [apiError, setApiError] = useState("");
  const mutation = useCreatePlatformBillingInvoice();
  const {
    control,
    formState: { errors },
    handleSubmit,
    register,
    reset,
    setValue,
  } = useForm<CreatePlatformBillingInvoiceValues>({
    defaultValues: emptyValues,
    resolver: zodResolver(createPlatformBillingInvoiceSchema),
  });
  const companyId = useWatch({ control, name: "companyId" });
  const planId = useWatch({ control, name: "planId" });
  const subscriptionQuery = usePlatformCompanySubscription(
    companyId,
    isOpen && !!companyId,
  );
  const activePlans = useMemo(
    () => plans.filter((plan) => plan.isActive),
    [plans],
  );

  useEffect(() => {
    if (isOpen) {
      reset(emptyValues);
    }
  }, [isOpen, reset]);

  useEffect(() => {
    if (subscriptionQuery.data) {
      setValue("subscriptionId", subscriptionQuery.data.id);
      setValue("planId", subscriptionQuery.data.plan.id);
      setValue("amount", Number(subscriptionQuery.data.plan.price ?? 0));
      setValue("billingPeriodStart", subscriptionQuery.data.startDate);
      setValue("billingPeriodEnd", subscriptionQuery.data.endDate);
    } else if (companyId && subscriptionQuery.isError) {
      setValue("subscriptionId", "");
    }
  }, [companyId, setValue, subscriptionQuery.data, subscriptionQuery.isError]);

  useEffect(() => {
    const selectedPlan = activePlans.find((plan) => plan.id === planId);
    if (selectedPlan) {
      setValue("amount", Number(selectedPlan.price ?? 0));
    }
  }, [activePlans, planId, setValue]);

  if (!isOpen) {
    return null;
  }

  function handleClose() {
    if (!mutation.isPending) {
      setApiError("");
      onClose();
    }
  }

  function onSubmit(values: CreatePlatformBillingInvoiceValues) {
    setApiError("");
    mutation.mutate(
      {
        companyId: values.companyId,
        payload: {
          amount: values.amount,
          billingPeriodEnd: values.billingPeriodEnd,
          billingPeriodStart: values.billingPeriodStart,
          dueDate: values.dueDate,
          notes: normalizeOptional(values.notes),
          planId: normalizeOptional(values.planId),
          subscriptionId: normalizeOptional(values.subscriptionId),
        },
      },
      {
        onError: (error) => {
          setApiError(
            getBillingMutationError(getApiErrorMessage(error)),
          );
        },
        onSuccess: () => {
          setApiError("");
          onClose();
        },
      },
    );
  }

  return (
    <div className="fixed inset-0 z-50">
      <button
        aria-label="Close billing invoice form"
        className="absolute inset-0 bg-foreground/30"
        type="button"
        onClick={handleClose}
      />
      <aside className="absolute right-0 top-0 flex h-full w-full max-w-xl flex-col bg-surface shadow-2xl">
        <div className="flex items-start justify-between gap-4 border-b border-border p-5">
          <div>
            <h2 className="text-lg font-semibold text-foreground">
              Create Billing Invoice
            </h2>
            <p className="mt-1 text-sm text-muted-foreground">
              Invoice numbers are generated by the backend.
            </p>
          </div>
          <Button
            aria-label="Close"
            disabled={mutation.isPending}
            size="icon"
            variant="ghost"
            onClick={handleClose}
          >
            <X className="size-5" />
          </Button>
        </div>

        <form
          className="flex min-h-0 flex-1 flex-col"
          onSubmit={handleSubmit(onSubmit)}
        >
          <div className="flex-1 space-y-5 overflow-y-auto p-5">
            {apiError ? (
              <div className="rounded-lg border border-error/20 bg-error/10 px-3 py-2 text-sm text-error">
                {apiError}
              </div>
            ) : null}

            <Field error={errors.companyId?.message} id="billing-company" label="Company">
              <select
                id="billing-company"
                className={selectClassName}
                {...register("companyId")}
              >
                <option value="">Select company</option>
                {companies.map((company) => (
                  <option key={company.id} value={company.id}>
                    {company.name}
                  </option>
                ))}
              </select>
            </Field>

            {subscriptionQuery.data ? (
              <div className="rounded-lg border border-info/20 bg-info/10 px-3 py-2 text-sm text-info">
                Current subscription detected: {subscriptionQuery.data.plan.name}{" "}
                at {formatBillingMoney(subscriptionQuery.data.plan.price)}.
              </div>
            ) : null}

            <Field error={errors.planId?.message} id="billing-plan" label="Plan">
              <select
                id="billing-plan"
                className={selectClassName}
                {...register("planId")}
              >
                <option value="">Select plan</option>
                {activePlans.map((plan) => (
                  <option key={plan.id} value={plan.id}>
                    {plan.name}
                  </option>
                ))}
              </select>
            </Field>

            <input type="hidden" {...register("subscriptionId")} />

            <div className="grid gap-5 sm:grid-cols-2">
              <Field
                error={errors.billingPeriodStart?.message}
                id="billing-period-start"
                label="Billing Period Start"
              >
                <Input
                  id="billing-period-start"
                  aria-invalid={!!errors.billingPeriodStart}
                  type="date"
                  {...register("billingPeriodStart")}
                />
              </Field>
              <Field
                error={errors.billingPeriodEnd?.message}
                id="billing-period-end"
                label="Billing Period End"
              >
                <Input
                  id="billing-period-end"
                  aria-invalid={!!errors.billingPeriodEnd}
                  type="date"
                  {...register("billingPeriodEnd")}
                />
              </Field>
            </div>

            <div className="grid gap-5 sm:grid-cols-2">
              <Field error={errors.amount?.message} id="billing-amount" label="Amount">
                <Input
                  id="billing-amount"
                  aria-invalid={!!errors.amount}
                  min={0}
                  step="0.01"
                  type="number"
                  {...register("amount", { valueAsNumber: true })}
                />
              </Field>
              <Field error={errors.dueDate?.message} id="billing-due-date" label="Due Date">
                <Input
                  id="billing-due-date"
                  aria-invalid={!!errors.dueDate}
                  type="date"
                  {...register("dueDate")}
                />
              </Field>
            </div>

            <Field error={errors.notes?.message} id="billing-notes" label="Notes">
              <textarea
                id="billing-notes"
                className={textareaClassName}
                placeholder="Optional billing note"
                rows={4}
                {...register("notes")}
              />
            </Field>
          </div>

          <div className="flex flex-col-reverse gap-2 border-t border-border p-5 sm:flex-row sm:justify-end">
            <Button
              disabled={mutation.isPending}
              type="button"
              variant="outline"
              onClick={handleClose}
            >
              Cancel
            </Button>
            <Button isLoading={mutation.isPending} type="submit">
              Create Invoice
            </Button>
          </div>
        </form>
      </aside>
    </div>
  );
}

function Field({
  children,
  error,
  id,
  label,
}: {
  children: React.ReactNode;
  error?: string;
  id: string;
  label: string;
}) {
  return (
    <div className="space-y-2">
      <Label htmlFor={id}>{label}</Label>
      {children}
      {error ? <p className="text-sm text-error">{error}</p> : null}
    </div>
  );
}

const selectClassName = cn(
  "flex h-10 w-full rounded-lg border border-border bg-surface px-3 py-2",
  "text-sm text-foreground outline-none transition-colors",
  "focus:border-primary focus:ring-4 focus:ring-ring",
  "disabled:cursor-not-allowed disabled:bg-muted disabled:opacity-70",
);

const textareaClassName = cn(
  "flex w-full rounded-lg border border-border bg-surface px-3 py-2",
  "text-sm text-foreground outline-none transition-colors placeholder:text-muted-foreground",
  "focus:border-primary focus:ring-4 focus:ring-ring",
);
